import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "checking upload",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
// import "./globals.css";
// import { CartProvider } from "@/context/CartContext";
 
// export const metadata = {
//   title: "Luxe — Curated Essentials",
//   description: "A refined selection of everyday luxury",
// };
 
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <CartProvider>{children}</CartProvider>
//       </body>
//     </html>
//   );
// }